#cloud-config
package_update: true
write_files:
  - path: /etc/rancher/rke2/config.yaml
    owner: root
    content: |
      tls-san:
        - rke2a.lol
        - rke2a
        - rke2master.lol
        - rke2master
  - path: /etc/hosts
    owner: root
    content: |
      127.0.0.1 localhost
      127.0.0.1 rke2master
      10.0.1.2 rke2a
      10.0.1.3 rke2b 
      10.0.1.4 rke2c

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.20 sh -
  - mkdir -p /var/lib/rancher/rke2/server/manifests/
  - wget https://kube-vip.io/manifests/rbac.yaml -O /var/lib/rancher/rke2/server/manifests/kube-vip-rbac.yaml
  - curl -sL kube-vip.io/k3s |  vipAddress=10.2.0.5 vipInterface=enp1s0 sh | sudo tee /var/lib/rancher/rke2/server/manifests/vip.yaml
  - sed -i 's/k3s/rke2/g' /var/lib/rancher/rke2/server/manifests/vip.yaml
  - systemctl enable rke2-server.service
  - systemctl start rke2-server.service